### PR TITLE
Fixes Issue#69. `rake cassandra:reset` now drops, creates and loads db while `rake cassandra:setup` just creates and loads db

### PR DESCRIPTION
**Pull request by sstgithub**

### CODE REVIEW

**Comment by eprothro** [comment]
Any plan to merge this? As a new user, this is what I was expecting.

**Comment by bsbodden** [comment]
@sstgithub Any tests that we can add to this? I'll go ahead and merge it after a reply

**Comment by bsbodden** [comment]
Released gem version 0.2.4 with all the latest additions

**Comment by eprothro** [comment]
might not be something you're worried about, but will a 0.2.3 user be surprised at backwards incompatible changes to rake tasks?

**Pull request merged**
